version: '3.4'

services:
  serv_catalog:
    image: serv_catalog
    build:
      context: serv_catalog
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081

  dev_catalog:
    image: dev_catalog
    build:
      context: dev_catalog
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082

# EOF
