version: '3.4'

services:
  serv_catalog:
    image: serv_catalog
    build:
      context: serv_catalog
      dockerfile: ./Dockerfile
    # command: ["sh", "-c", "/bin/bash"]
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --listen 0.0.0.0:5678 --wait-for-client ./services_catalog.py"]
    ports:
      - 5678:5678
      - 8081:8081
    # environment:
    #   - FLASK_APP=serv_catalog/services_catalog.py
